version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: employee-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./employee-api
    container_name: employee-backend
    ports:
      # --- UPDATED HERE ---
      - "${HOST_PORT}:8080" 
      # Now it maps Host(8090) -> Container(8080)
    env_file:
      - .env
    environment:
      DB_HOST: db
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      # We do NOT pass HOST_PORT here, so Spring defaults to 8080
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: 
      context: ./employee-ui
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: employee-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: