apiVersion: v1
kind: Secret
metadata:
  name: db-secrets 
type: Opaque
data:
  # Key: EncodedValue
  # "root"
  mysql-root-password: cm9vdA==
  # "root" (for the app user password)
  mysql-user-password: cm9vdA==
  # "app_user"
  mysql-user: YXBwX3VzZXI=