name: Build and Push Docker Image

# 1. THE TRIGGER (When to wake up?)
on:
  push:
    branches: [ "main" ]

# 2. THE JOB (The Mission)
jobs:
  build-and-push:
    # 3. THE RUNNER (The Computer)
    runs-on: ubuntu-latest

    # 4. THE STEPS (The Checklist)
    steps:
      # Step A: Download the code from the repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step B: Log in to DockerHub (Using the Secrets)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step C: Build the Image and Push it
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./employee-api
          file: ./employee-api/Dockerfile
          push: true
          tags: sushantc041/backend:v2